apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp_v3.fullname" . }}
spec:
  selector:
    {{- include "myapp_v3.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
