apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp_v3.fullname" . }}
  labels:
    app: {{ include "myapp_v3.fullname" . }}-app
spec:
  selector:
    app: {{ include "myapp_v3.fullname" . }}-app
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
      name: serviceport
