apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp-benchmark2"
spec:
  template:
    metadata:
      name: "myapp-benchmark2"
    spec:
      restartPolicy: Never
      containers:
        - image: antonzylyov/ab:v1
          name: myapp-initdb-job
          env:
            - name: AB_REQUEST_COUNT
              value: "150"
            - name: AB_REQUEST_CONCURRENCY
              value: "20"
            - name: AB_TIMEOUT
              value: "300"
            - name: AB_URL
              value: "http://bit.homework/bitapp/zylyov/user/3"
  backoffLimit: 1
